// Common Components (Transversal/Shared components)
export { DocumentViewer } from './DocumentViewer';
export type { DocumentViewerProps } from './DocumentViewer';
export { PaymentStatusSelect } from './PaymentStatusSelect';
export { FinancialKPIs } from './FinancialKPIs';
export { ExpensesPieChart } from './ExpensesPieChart';
export { IncomeBarChart } from './IncomeBarChart';
export { IncomeExpenseComparisonChart } from './IncomeExpenseComparisonChart';
export { ExpensesAccumulatedChart } from './ExpensesAccumulatedChart';
export { StatCard } from './StatCard';
export { ChartTooltip, formatCurrencyTooltip } from './ChartTooltip';
export { QuickNavCards } from './QuickNavCards';
export { EmptyState } from './EmptyState';
export { Popover } from './Popover';
export type { PopoverProps } from './Popover';
export { ListViewHeader } from './ListViewHeader';
export type { ListViewHeaderProps, ViewType } from './ListViewHeader';
export { EntityTableView } from './EntityTableView';
export type { EntityTableViewProps, EntityTableItem } from './EntityTableView';
export { EntityCardsView } from './EntityCardsView';
export type { EntityCardsViewProps, EntityCardItem } from './EntityCardsView';
export { UniversalSearchBar } from './UniversalSearchBar';
export type { UniversalSearchBarProps } from './UniversalSearchBar';